name: 'openpilot env setup'

runs:
  using: "composite"
  steps:
    # do this after checkout to ensure our custom LFS config is used to pull from GitLab
    - shell: bash
      run: git lfs pull
    # normalize the file permissions for scripts and files used within the docker build for a consistent cache
    - shell: bash
      name: Normalize file permissions
      run: |
        chmod 644 Dockerfile.openpilot_base poetry.lock pyproject.toml .python-version
        chmod 755 tools/ubuntu_setup.sh tools/install_python_dependencies.sh
    # build cache
    - id: date
      shell: bash
      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
    - shell: bash
      run: echo "$CACHE_COMMIT_DATE"
    - id: restore-scons-cache
      uses: actions/cache/restore@v3
      with:
        path: ~/scons_cache
        key: scons-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
        restore-keys: |
          scons-${{ env.CACHE_COMMIT_DATE }}-
          scons-

    # build our docker image
    - shell: bash
      run: eval ${{ env.BUILD }}
